services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Edgar\EzUISitesBundle\EventListener\ConfigureMenuListener:
        public: true
        tags:
            - { name: kernel.event_listener, event: ezplatform_admin_ui.menu_configure.main_menu, method: onMenuConfigure }
